// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleApi.Infra.Data.Contexts;

#nullable disable

namespace SimpleApi.Infra.Data.Migrations
{
    [DbContext(typeof(SimpleApiContext))]
    [Migration("20220717190216_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleApi.Domain.Entitys.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("PageNumbers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredIn")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
